<h1><?php echo $data->title ?></h1>
<?php
if ($data->byline) {
	?>
	<p>
		<em><?php printf(__("by %s", "medium"), $data->byline); ?></em>
	</p>
	<?php
}
echo $data->content;
if ($data->cross_link) {
	?>
	<hr class="medium-cross-link-hr">
	<div class="medium-cross-link">
	<p>
		<em>
			<?php
		  $link = sprintf('<a href="%s">%s</a>', $data->permalink, $data->site_name);
		  printf(__("Originally published at %s.", "medium"), $link);
		  ?>
		</em>
	</p>
	</div>
	<?php
}
