<div class="misc-pub-section misc-pub-medium-status">
	<div class="post-medium-images">
		<a href="https://medium.com"><img class="post-medium-image post-medium-image-logo" src="<?= $data->medium_logo_url ?>"/></a>
		<a href="<?= $data->medium_post->author_url ?>"><img class="post-medium-image post-medium-image-avatar" src="<?= $data->medium_post->author_image_url ?>"/></a>
	</div>
	<div id="medium-post-link">
		<b><a href="<?= $data->medium_post->url ?>" target="_blank">View Medium post</a></b>
		<p>Further edits to this entry will not be reflected on Medium.</p>
	</div>
</div>
