<div class="misc-pub-section misc-pub-medium-status">
	<div class="post-medium-images">
		<a href="<?php echo $data->medium_post->author_url ?>"><img class="post-medium-image post-medium-image-avatar" src="<?php echo $data->medium_post->author_image_url ?>"/></a>
		<a href="https://medium.com"><img class="post-medium-image post-medium-image-logo" src="<?php echo $data->medium_logo_url ?>"/></a>
	</div>
	<div id="medium-post-link">
		<b><a href="<?php echo $data->medium_post->url ?>" target="_blank"><?php _e("View Medium post", "medium") ?></a></b>
		<p><?php _e("Further edits to this entry will not be reflected on Medium.", "medium") ?></p>
	</div>
</div>
