<h3 id="medium"><?php _e( 'Medium', 'medium' ) ?></h3>
<table class="form-table">
	<tr>
		<th><label for="medium_integration_token"><?php _e( 'Integration Token', 'medium' ) ?></label></th>
		<td>
			<input type="text" name="medium_integration_token" id="medium_integration_token" value="<?= $data->medium_user->token ?>" class="regular-text" /><br />
			<?php if ( $data->medium_user->token ) : ?>
				<p class="description">
					<?php
					printf(
						_x( 'Connected to Medium as %s.', 'medium', 'Medium user profile link' ),
						sprintf(
							'<a href="%s">%s</a>',
							esc_url( $data->medium_user->url ),
							esc_html( $data->medium_user->name )
						)
					)
					?>
				</p>
			<?php else : ?>
				<p class="description">
					<?php
					printf(
						_x( 'You can get this from the Integration Tokens section of your %s.', 'medium', 'Medium settings link' ),
						sprintf(
							'<a href="https://medium.com/me/settings#integration-tokens" target="_blank">%s</a>',
							__( 'Medium Settings', 'medium' )
						)
					)
					?>
				</p>
			<?php endif; ?>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_post_status"><?php _e( 'Default crosspost status', 'medium' ) ?></label></th>
		<td>
			<select name="medium_default_post_status" id="medium_default_post_status">
				<?php
				foreach ($data->medium_post_statuses as $status => $label) {
					?>
					<option value="<?= $status ?>" <?php selected($data->medium_user->default_status, $status) ?>><?= $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description">
				<?php _e( 'The default status to use when creating a post on Medium. Unlisted posts will not be indexed, nor distributed through Medium. Can be changed for each post.', 'medium' ) ?>
			</p>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_post_license"><?php _e( 'Default crosspost license', 'medium' ) ?></label></th>
		<td>
			<select name="medium_default_post_license" id="medium_default_post_license">
				<?php
				foreach ($data->medium_post_licenses as $license => $label) {
					?>
					<option value="<?= $license ?>" <?php selected($data->medium_user->default_license, $license) ?>><?= $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description">
				<?php _e( 'The default license to use when creating a post on Medium. Does not display any license information locally. Can be changed for each post.', 'medium' ) ?><br>
			</p>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_post_cross_link"><?php _e( 'Default cross-link status', 'medium' ) ?></label></th>
		<td>
			<select name="medium_default_post_cross_link" id="medium_default_post_cross_link">
				<?php
				foreach ($data->medium_post_cross_link_options as $cross_link => $label) {
					?>
					<option value="<?= $cross_link ?>" <?php selected($data->medium_user->default_cross_link, $cross_link) ?>><?= $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description">
				<?php _e( 'Whether or not to cross-link posts between this blog and Medium. When enabled adds a link to the bottom of both your local post, and the Medium post. Can be changed for each post.', 'medium' ) ?>
			</p>
		</td>
	</tr>
</table>
