<h3 id="medium"><?php _e("Medium", "medium") ?></h3>
<table class="form-table">
	<tr>
		<th><label for="medium_integration_token"><?php _e("Integration Token", "medium") ?></label></th>
		<td>
			<input type="text" name="medium_integration_token" id="medium_integration_token" value="<?php echo $data->medium_user->token ?>" class="regular-text" /><br />
			<?php
			if ($data->medium_user->token) {
				$userLink = sprintf('<a href="%s">%s</a>', $data->medium_user->url, $data->medium_user->name);
				?>
				<p class="description"><?php printf(__("Connected to Medium as %s.", "medium"), $userLink) ?><p>
				<?php
			} else {
				$settingsLink = sprintf('<a href="https://medium.com/me/settings#integration-tokens" target="_blank">%s</a>', __("your Medium Settings", "medium"));
				?>
				<p class="description"><?php printf(__("You can get this from the Integration Tokens section of %s.", "medium"), $settingsLink) ?></p>
				<?php
			}
			?>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_post_status"><?php _e("Default cross-post status", "medium") ?></label></th>
		<td>
			<select name="medium_default_post_status" id="medium_default_post_status">
				<?php
				foreach ($data->medium_post_statuses as $status => $label) {
					?>
					<option value="<?php echo $status ?>" <?php selected($data->medium_user->default_status, $status) ?>><?php echo $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description medium-wrapped">
				<?php _e("The default status to use when creating a post on Medium. Unlisted posts will not be indexed, nor distributed through Medium. Can be changed for each post.", "medium"); ?>
			</p>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_post_license"><?php _e("Default cross-post license", "medium") ?></label></th>
		<td>
			<select name="medium_default_post_license" id="medium_default_post_license">
				<?php
				foreach ($data->medium_post_licenses as $license => $label) {
					?>
					<option value="<?php echo $license ?>" <?php selected($data->medium_user->default_license, $license) ?>><?php echo $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description medium-wrapped">
				<?php _e("The default license to use when creating a post on Medium. Does not display any license information locally. Can be changed for each post.", "medium"); ?>
			</p>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_post_cross_link"><?php _e("Default cross-link status", "medium") ?></label></th>
		<td>
			<select name="medium_default_post_cross_link" id="medium_default_post_cross_link">
				<?php
				foreach ($data->medium_boolean_options as $boolean => $label) {
					?>
					<option value="<?php echo $boolean ?>" <?php selected($data->medium_user->default_cross_link, $boolean) ?>><?php echo $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description medium-wrapped">
				<?php _e("Whether or not to cross-link posts between this blog and Medium. When enabled adds a link to the bottom of both your local post, and the Medium post. Can be changed for each post.", "medium"); ?>
			</p>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_follower_notification"><?php _e("Default follower notification", "medium") ?></label></th>
		<td>
			<select name="medium_default_follower_notification" id="medium_default_follower_notification">
				<?php
				foreach ($data->medium_boolean_options as $boolean => $label) {
					?>
					<option value="<?php echo $boolean ?>" <?php selected($data->medium_user->default_follower_notification, $boolean) ?>><?php echo $label ?></option>
					<?php
				}
				?>
			</select>
			<p class="description medium-wrapped">
				<?php _e("Whether or not to notify your Medium followers when the post is sent to Medium. Can be changed for each post.", "medium"); ?>
			</p>
		</td>
	</tr>
	<tr>
		<th><label for="medium_default_publication_id"><?php _e("Default cross-post publication", "medium") ?></label></th>
		<td>
				<select name="medium_default_publication_id" id="medium_default_publication_id">
					<?php
						foreach ($data->medium_publication_options as $publication_id => $publication) {
							?>
							<option data-publishable="<?php echo $publication->publishable ?>" value="<?php echo $publication_id ?>" <?php selected($data->medium_user->default_publication_id, $publication_id) ?>><?php echo $publication->name ?></option>
							<?php
						}
					?>
				</select>
				<?php
				if ($data->medium_user->token) {
					?>
					<button type="button" data-user-id="<?php echo $data->user_id ?>" id="medium-refresh-publications" class="button button-secondary hide-if-no-js"><?php _e("Refresh Publications", "medium") ?></button>
					<?php
				}
				?>
			<p id="medium-publications-description" class="description medium-wrapped">
				<?php _e("The publication on Medium to submit the post to. Can be changed for each post.", "medium"); ?>
			</p>
		</td>
	</tr>
</table>
